import fs from 'node:fs';
import path from 'node:path';

import Assert from '../core/Assert.js';

import Workspace from '../enums/Workspace.js';

const GENERATED_FILE_SUFFIX = '_pb.js';

const DESCRIPTOR_EXPORT_PATTERN = /^export const (file_\w+) =/m;

const HEADER = '// @generated by @deademx/tools';

/**
 * @typedef {{ file: string, descriptor: string }} ProtoIndexEntry
 */

class ProtoIndexWriter {
    /**
     * Writes `index.js` and `index.d.ts` into the generated directory of [workspace].
     *
     * @public
     * @static
     * @param {Workspace} workspace
     */
    static write(workspace) {
        Assert.isTrue(workspace instanceof Workspace && workspace.game);

        const directory = workspace.protoGeneratedDirectory;
        const entries = ProtoIndexWriter._collectEntries(directory);

        fs.writeFileSync(path.join(directory, 'index.js'), ProtoIndexWriter._renderModule(entries));
        fs.writeFileSync(path.join(directory, 'index.d.ts'), ProtoIndexWriter._renderDeclarations(entries));
    }

    /**
     * Generated files of [directory], sorted.
     *
     * @private
     * @static
     * @param {string} directory
     * @returns {Array<ProtoIndexEntry>}
     */
    static _collectEntries(directory) {
        return fs.readdirSync(directory)
            .filter(file => file.endsWith(GENERATED_FILE_SUFFIX))
            .sort()
            .map(file => ({ file, descriptor: ProtoIndexWriter._getDescriptorExport(path.join(directory, file)) }));
    }

    /**
     * @private
     * @static
     * @param {Array<ProtoIndexEntry>} entries
     * @returns {string}
     */
    static _renderModule(entries) {
        return `${HEADER}

import { createRegistry } from '@bufbuild/protobuf';

${entries.map(entry => `import { ${entry.descriptor} } from './${entry.file}';`).join('\n')}

${ProtoIndexWriter._renderReexports(entries)}

export const descriptors = createRegistry(
${entries.map(entry => `    ${entry.descriptor}`).join(',\n')}
);
`;
    }

    /**
     * @private
     * @static
     * @param {Array<ProtoIndexEntry>} entries
     * @returns {string}
     */
    static _renderDeclarations(entries) {
        return `${HEADER}

import type { Registry } from '@bufbuild/protobuf';

${ProtoIndexWriter._renderReexports(entries)}

export declare const descriptors: Registry;
`;
    }

    /**
     * @private
     * @static
     * @param {Array<ProtoIndexEntry>} entries
     * @returns {string}
     */
    static _renderReexports(entries) {
        return entries.map(entry => `export * from './${entry.file}';`).join('\n');
    }

    /**
     * @private
     * @static
     * @param {string} file
     * @returns {string}
     */
    static _getDescriptorExport(file) {
        const match = fs.readFileSync(file, 'utf-8').match(DESCRIPTOR_EXPORT_PATTERN);

        Assert.isTrue(match !== null, `No file descriptor export in [ ${file} ]`);

        return match[1];
    }
}

export default ProtoIndexWriter;
