/**
 * A decoder generated by `@deademx/tools`.
 *
 * @template [T=Record<string, any>]
 * @typedef {object} ProtoDecoder
 * @property {(buffer: Uint8Array) => T} decode
 * @property {Record<number, ProtoField>} fields
 * @property {Record<string, ProtoDecoder>} registry
 */

/**
 * @typedef {object} ProtoField
 * @property {string} name
 * @property {string} type
 * @property {boolean} [repeated]
 * @property {string} [resolved]
 * @property {boolean} [long]
 * @property {boolean} [bytes]
 * @property {unknown} fallback
 */

export { };
