import EngineBootstrap from '@deadem/engine/src/Bootstrap.js';

import MessagePacketType from '#data/enums/MessagePacketType.js';

class Bootstrap extends EngineBootstrap {
    /**
     * @public
     * @static
     * @param {ProtoProvider} pp
     */
    static run(pp) {
        super.run(pp);

        Bootstrap._initDotaUserMessages(pp);
    }

    static _initDotaUserMessages(pp) {
        const um = pp.DOTA_USER_MESSAGES;

        MessagePacketType.DOTA_UM_AI_DEBUG_LINE.proto = um.lookupType('CDOTAUserMsg_AIDebugLine');
        MessagePacketType.DOTA_UM_CHAT_EVENT.proto = um.lookupType('CDOTAUserMsg_ChatEvent');
        MessagePacketType.DOTA_UM_COMBAT_HERO_POSITIONS.proto = um.lookupType('CDOTAUserMsg_CombatHeroPositions');
        MessagePacketType.DOTA_UM_COMBAT_LOG_BULK_DATA.proto = um.lookupType('CDOTAUserMsg_CombatLogBulkData');
        MessagePacketType.DOTA_UM_CREATE_LINEAR_PROJECTILE.proto = um.lookupType('CDOTAUserMsg_CreateLinearProjectile');
        MessagePacketType.DOTA_UM_DESTROY_LINEAR_PROJECTILE.proto = um.lookupType('CDOTAUserMsg_DestroyLinearProjectile');
        MessagePacketType.DOTA_UM_DODGE_TRACKING_PROJECTILES.proto = um.lookupType('CDOTAUserMsg_DodgeTrackingProjectiles');
        MessagePacketType.DOTA_UM_GLOBAL_LIGHT_COLOR.proto = um.lookupType('CDOTAUserMsg_GlobalLightColor');
        MessagePacketType.DOTA_UM_GLOBAL_LIGHT_DIRECTION.proto = um.lookupType('CDOTAUserMsg_GlobalLightDirection');
        MessagePacketType.DOTA_UM_INVALID_COMMAND.proto = um.lookupType('CDOTAUserMsg_InvalidCommand');
        MessagePacketType.DOTA_UM_LOCATION_PING.proto = um.lookupType('CDOTAUserMsg_LocationPing');
        MessagePacketType.DOTA_UM_MAP_LINE.proto = um.lookupType('CDOTAUserMsg_MapLine');
        MessagePacketType.DOTA_UM_MINI_KILL_CAM_INFO.proto = um.lookupType('CDOTAUserMsg_MiniKillCamInfo');
        MessagePacketType.DOTA_UM_MINIMAP_DEBUG_POINT.proto = um.lookupType('CDOTAUserMsg_MinimapDebugPoint');
        MessagePacketType.DOTA_UM_MINIMAP_EVENT.proto = um.lookupType('CDOTAUserMsg_MinimapEvent');
        MessagePacketType.DOTA_UM_NEVERMORE_REQUIEM.proto = um.lookupType('CDOTAUserMsg_NevermoreRequiem');
        MessagePacketType.DOTA_UM_OVERHEAD_EVENT.proto = um.lookupType('CDOTAUserMsg_OverheadEvent');
        MessagePacketType.DOTA_UM_SET_NEXT_AUTOBUY_ITEM.proto = um.lookupType('CDOTAUserMsg_SetNextAutobuyItem');
        MessagePacketType.DOTA_UM_SHARED_COOLDOWN.proto = um.lookupType('CDOTAUserMsg_SharedCooldown');
        MessagePacketType.DOTA_UM_SPECTATOR_PLAYER_CLICK.proto = um.lookupType('CDOTAUserMsg_SpectatorPlayerClick');
        MessagePacketType.DOTA_UM_TUTORIAL_TIP_INFO.proto = um.lookupType('CDOTAUserMsg_TutorialTipInfo');
        MessagePacketType.DOTA_UM_UNIT_EVENT.proto = um.lookupType('CDOTAUserMsg_UnitEvent');
        MessagePacketType.DOTA_UM_BOT_CHAT.proto = um.lookupType('CDOTAUserMsg_BotChat');
        MessagePacketType.DOTA_UM_HUD_ERROR.proto = um.lookupType('CDOTAUserMsg_HudError');
        MessagePacketType.DOTA_UM_ITEM_PURCHASED.proto = um.lookupType('CDOTAUserMsg_ItemPurchased');
        MessagePacketType.DOTA_UM_PING.proto = um.lookupType('CDOTAUserMsg_Ping');
        MessagePacketType.DOTA_UM_ITEM_FOUND.proto = um.lookupType('CDOTAUserMsg_ItemFound');
        MessagePacketType.DOTA_UM_SWAP_VERIFY.proto = um.lookupType('CDOTAUserMsg_SwapVerify');
        MessagePacketType.DOTA_UM_WORLD_LINE.proto = um.lookupType('CDOTAUserMsg_WorldLine');
        MessagePacketType.DOTA_UM_ITEM_ALERT.proto = um.lookupType('CDOTAUserMsg_ItemAlert');
        MessagePacketType.DOTA_UM_HALLOWEEN_DROPS.proto = um.lookupType('CDOTAUserMsg_HalloweenDrops');
        MessagePacketType.DOTA_UM_CHAT_WHEEL.proto = um.lookupType('CDOTAUserMsg_ChatWheel');
        MessagePacketType.DOTA_UM_RECEIVED_XMAS_GIFT.proto = um.lookupType('CDOTAUserMsg_ReceivedXmasGift');
        MessagePacketType.DOTA_UM_UPDATE_SHARED_CONTENT.proto = um.lookupType('CDOTAUserMsg_UpdateSharedContent');
        MessagePacketType.DOTA_UM_TUTORIAL_REQUEST_EXP.proto = um.lookupType('CDOTAUserMsg_TutorialRequestExp');
        MessagePacketType.DOTA_UM_TUTORIAL_PING_MINIMAP.proto = um.lookupType('CDOTAUserMsg_TutorialPingMinimap');
        MessagePacketType.DOTA_UM_GAMERULES_STATE_CHANGED.proto = um.lookupType('CDOTAUserMsg_GamerulesStateChanged');
        MessagePacketType.DOTA_UM_SHOW_SURVEY.proto = um.lookupType('CDOTAUserMsg_ShowSurvey');
        MessagePacketType.DOTA_UM_TUTORIAL_FADE.proto = um.lookupType('CDOTAUserMsg_TutorialFade');
        MessagePacketType.DOTA_UM_ADD_QUEST_LOG_ENTRY.proto = um.lookupType('CDOTAUserMsg_AddQuestLogEntry');
        MessagePacketType.DOTA_UM_SEND_STAT_POPUP.proto = um.lookupType('CDOTAUserMsg_SendStatPopup');
        MessagePacketType.DOTA_UM_TUTORIAL_FINISH.proto = um.lookupType('CDOTAUserMsg_TutorialFinish');
        MessagePacketType.DOTA_UM_SEND_ROSHAN_POPUP.proto = um.lookupType('CDOTAUserMsg_SendRoshanPopup');
        MessagePacketType.DOTA_UM_SEND_GENERIC_TOOL_TIP.proto = um.lookupType('CDOTAUserMsg_SendGenericToolTip');
        MessagePacketType.DOTA_UM_SEND_FINAL_GOLD.proto = um.lookupType('CDOTAUserMsg_SendFinalGold');
        MessagePacketType.DOTA_UM_CUSTOM_MSG.proto = um.lookupType('CDOTAUserMsg_CustomMsg');
        MessagePacketType.DOTA_UM_COACH_HUD_PING.proto = um.lookupType('CDOTAUserMsg_CoachHUDPing');
        MessagePacketType.DOTA_UM_CLIENT_LOAD_GRID_NAV.proto = um.lookupType('CDOTAUserMsg_ClientLoadGridNav');
        MessagePacketType.DOTA_UM_TE_PROJECTILE.proto = um.lookupType('CDOTAUserMsg_TE_Projectile');
        MessagePacketType.DOTA_UM_TE_PROJECTILE_LOC.proto = um.lookupType('CDOTAUserMsg_TE_ProjectileLoc');
        MessagePacketType.DOTA_UM_TE_DOTA_BLOOD_IMPACT.proto = um.lookupType('CDOTAUserMsg_TE_DotaBloodImpact');
        MessagePacketType.DOTA_UM_TE_UNIT_ANIMATION.proto = um.lookupType('CDOTAUserMsg_TE_UnitAnimation');
        MessagePacketType.DOTA_UM_TE_UNIT_ANIMATION_END.proto = um.lookupType('CDOTAUserMsg_TE_UnitAnimationEnd');
        MessagePacketType.DOTA_UM_ABILITY_PING.proto = um.lookupType('CDOTAUserMsg_AbilityPing');
        MessagePacketType.DOTA_UM_SHOW_GENERIC_POPUP.proto = um.lookupType('CDOTAUserMsg_ShowGenericPopup');
        MessagePacketType.DOTA_UM_VOTE_START.proto = um.lookupType('CDOTAUserMsg_VoteStart');
        MessagePacketType.DOTA_UM_VOTE_UPDATE.proto = um.lookupType('CDOTAUserMsg_VoteUpdate');
        MessagePacketType.DOTA_UM_VOTE_END.proto = um.lookupType('CDOTAUserMsg_VoteEnd');
        MessagePacketType.DOTA_UM_BOOSTER_STATE.proto = um.lookupType('CDOTAUserMsg_BoosterState');
        MessagePacketType.DOTA_UM_WILL_PURCHASE_ALERT.proto = um.lookupType('CDOTAUserMsg_WillPurchaseAlert');
        MessagePacketType.DOTA_UM_TUTORIAL_MINIMAP_POSITION.proto = um.lookupType('CDOTAUserMsg_TutorialMinimapPosition');
        MessagePacketType.DOTA_UM_ABILITY_STEAL.proto = um.lookupType('CDOTAUserMsg_AbilitySteal');
        MessagePacketType.DOTA_UM_COURIER_KILLED_ALERT.proto = um.lookupType('CDOTAUserMsg_CourierKilledAlert');
        MessagePacketType.DOTA_UM_ENEMY_ITEM_ALERT.proto = um.lookupType('CDOTAUserMsg_EnemyItemAlert');
        MessagePacketType.DOTA_UM_STATS_MATCH_DETAILS.proto = um.lookupType('CDOTAUserMsg_StatsMatchDetails');
        MessagePacketType.DOTA_UM_MINI_TAUNT.proto = um.lookupType('CDOTAUserMsg_MiniTaunt');
        MessagePacketType.DOTA_UM_BUY_BACK_STATE_ALERT.proto = um.lookupType('CDOTAUserMsg_BuyBackStateAlert');
        MessagePacketType.DOTA_UM_SPEECH_BUBBLE.proto = um.lookupType('CDOTAUserMsg_SpeechBubble');
        MessagePacketType.DOTA_UM_CUSTOM_HEADER_MESSAGE.proto = um.lookupType('CDOTAUserMsg_CustomHeaderMessage');
        MessagePacketType.DOTA_UM_QUICK_BUY_ALERT.proto = um.lookupType('CDOTAUserMsg_QuickBuyAlert');
        MessagePacketType.DOTA_UM_MODIFIER_ALERT.proto = um.lookupType('CDOTAUserMsg_ModifierAlert');
        MessagePacketType.DOTA_UM_HP_MANA_ALERT.proto = um.lookupType('CDOTAUserMsg_HPManaAlert');
        MessagePacketType.DOTA_UM_GLYPH_ALERT.proto = um.lookupType('CDOTAUserMsg_GlyphAlert');
        MessagePacketType.DOTA_UM_BEAST_CHAT.proto = um.lookupType('CDOTAUserMsg_BeastChat');
        MessagePacketType.DOTA_UM_SPECTATOR_PLAYER_UNIT_ORDERS.proto = um.lookupType('CDOTAUserMsg_SpectatorPlayerUnitOrders');
        MessagePacketType.DOTA_UM_CUSTOM_HUD_ELEMENT_CREATE.proto = um.lookupType('CDOTAUserMsg_CustomHudElement_Create');
        MessagePacketType.DOTA_UM_CUSTOM_HUD_ELEMENT_MODIFY.proto = um.lookupType('CDOTAUserMsg_CustomHudElement_Modify');
        MessagePacketType.DOTA_UM_CUSTOM_HUD_ELEMENT_DESTROY.proto = um.lookupType('CDOTAUserMsg_CustomHudElement_Destroy');
        MessagePacketType.DOTA_UM_COMPENDIUM_STATE.proto = um.lookupType('CDOTAUserMsg_CompendiumState');
        MessagePacketType.DOTA_UM_PROJECTION_ABILITY.proto = um.lookupType('CDOTAUserMsg_ProjectionAbility');
        MessagePacketType.DOTA_UM_PROJECTION_EVENT.proto = um.lookupType('CDOTAUserMsg_ProjectionEvent');
        MessagePacketType.DOTA_UM_COMBAT_LOG_DATA_HLTV.proto = um.lookupType('CMsgDOTACombatLogEntry');
        MessagePacketType.DOTA_UM_XP_ALERT.proto = um.lookupType('CDOTAUserMsg_XPAlert');
        MessagePacketType.DOTA_UM_UPDATE_QUEST_PROGRESS.proto = um.lookupType('CDOTAUserMsg_UpdateQuestProgress');
        MessagePacketType.DOTA_UM_QUEST_STATUS.proto = um.lookupType('CDOTAUserMsg_QuestStatus');
        MessagePacketType.DOTA_UM_SUGGEST_HERO_PICK.proto = um.lookupType('CDOTAUserMsg_SuggestHeroPick');
        MessagePacketType.DOTA_UM_SUGGEST_HERO_ROLE.proto = um.lookupType('CDOTAUserMsg_SuggestHeroRole');
        MessagePacketType.DOTA_UM_KILLCAM_DAMAGE_TAKEN.proto = um.lookupType('CDOTAUserMsg_KillcamDamageTaken');
        MessagePacketType.DOTA_UM_SELECT_PENALTY_GOLD.proto = um.lookupType('CDOTAUserMsg_SelectPenaltyGold');
        MessagePacketType.DOTA_UM_ROLL_DICE_RESULT.proto = um.lookupType('CDOTAUserMsg_RollDiceResult');
        MessagePacketType.DOTA_UM_FLIP_COIN_RESULT.proto = um.lookupType('CDOTAUserMsg_FlipCoinResult');
        MessagePacketType.DOTA_UM_REQUEST_ITEM_SUGGESTIONS.proto = um.lookupType('CDOTAUserMessage_RequestItemSuggestions');
        MessagePacketType.DOTA_UM_TEAM_CAPTAIN_CHANGED.proto = um.lookupType('CDOTAUserMessage_TeamCaptainChanged');
        MessagePacketType.DOTA_UM_SEND_ROSHAN_SPECTATOR_PHASE.proto = um.lookupType('CDOTAUserMsg_SendRoshanSpectatorPhase');
        MessagePacketType.DOTA_UM_CHAT_WHEEL_COOLDOWN.proto = um.lookupType('CDOTAUserMsg_ChatWheelCooldown');
        MessagePacketType.DOTA_UM_DISMISS_ALL_STAT_POPUPS.proto = um.lookupType('CDOTAUserMsg_DismissAllStatPopups');
        MessagePacketType.DOTA_UM_TE_DESTROY_PROJECTILE.proto = um.lookupType('CDOTAUserMsg_TE_DestroyProjectile');
        MessagePacketType.DOTA_UM_HERO_RELIC_PROGRESS.proto = um.lookupType('CDOTAUserMsg_HeroRelicProgress');
        MessagePacketType.DOTA_UM_ABILITY_DRAFT_REQUEST_ABILITY.proto = um.lookupType('CDOTAUserMsg_AbilityDraftRequestAbility');
        MessagePacketType.DOTA_UM_ITEM_SOLD.proto = um.lookupType('CDOTAUserMsg_ItemSold');
        MessagePacketType.DOTA_UM_DAMAGE_REPORT.proto = um.lookupType('CDOTAUserMsg_DamageReport');
        MessagePacketType.DOTA_UM_SALUTE_PLAYER.proto = um.lookupType('CDOTAUserMsg_SalutePlayer');
        MessagePacketType.DOTA_UM_TIP_ALERT.proto = um.lookupType('CDOTAUserMsg_TipAlert');
        MessagePacketType.DOTA_UM_REPLACE_QUERY_UNIT.proto = um.lookupType('CDOTAUserMsg_ReplaceQueryUnit');
        MessagePacketType.DOTA_UM_EMPTY_TELEPORT_ALERT.proto = um.lookupType('CDOTAUserMsg_EmptyTeleportAlert');
        MessagePacketType.DOTA_UM_MARS_ARENA_OF_BLOOD_ATTACK.proto = um.lookupType('CDOTAUserMsg_MarsArenaOfBloodAttack');
        MessagePacketType.DOTA_UM_ES_ARCANA_COMBO.proto = um.lookupType('CDOTAUserMsg_ESArcanaCombo');
        MessagePacketType.DOTA_UM_ES_ARCANA_COMBO_SUMMARY.proto = um.lookupType('CDOTAUserMsg_ESArcanaComboSummary');
        MessagePacketType.DOTA_UM_HIGH_FIVE_LEFT_HANGING.proto = um.lookupType('CDOTAUserMsg_HighFiveLeftHanging');
        MessagePacketType.DOTA_UM_HIGH_FIVE_COMPLETED.proto = um.lookupType('CDOTAUserMsg_HighFiveCompleted');
        MessagePacketType.DOTA_UM_SHOVEL_UNEARTH.proto = um.lookupType('CDOTAUserMsg_ShovelUnearth');
        MessagePacketType.DOTA_UM_RADAR_ALERT.proto = um.lookupType('CDOTAUserMsg_RadarAlert');
        MessagePacketType.DOTA_UM_ALL_STAR_EVENT.proto = um.lookupType('CDOTAUserMsg_AllStarEvent');
        MessagePacketType.DOTA_UM_TALENT_TREE_ALERT.proto = um.lookupType('CDOTAUserMsg_TalentTreeAlert');
        MessagePacketType.DOTA_UM_QUEUED_ORDER_REMOVED.proto = um.lookupType('CDOTAUserMsg_QueuedOrderRemoved');
        MessagePacketType.DOTA_UM_DEBUG_CHALLENGE.proto = um.lookupType('CDOTAUserMsg_DebugChallenge');
        MessagePacketType.DOTA_UM_OM_ARCANA_COMBO.proto = um.lookupType('CDOTAUserMsg_OMArcanaCombo');
        MessagePacketType.DOTA_UM_FOUND_NEUTRAL_ITEM.proto = um.lookupType('CDOTAUserMsg_FoundNeutralItem');
        MessagePacketType.DOTA_UM_OUTPOST_CAPTURED.proto = um.lookupType('CDOTAUserMsg_OutpostCaptured');
        MessagePacketType.DOTA_UM_OUTPOST_GRANTED_XP.proto = um.lookupType('CDOTAUserMsg_OutpostGrantedXP');
        MessagePacketType.DOTA_UM_MOVE_CAMERA_TO_UNIT.proto = um.lookupType('CDOTAUserMsg_MoveCameraToUnit');
        MessagePacketType.DOTA_UM_PAUSE_MINIGAME_DATA.proto = um.lookupType('CDOTAUserMsg_PauseMinigameData');
        MessagePacketType.DOTA_UM_VERSUS_SCENE_PLAYER_BEHAVIOR.proto = um.lookupType('CDOTAUserMsg_VersusScene_PlayerBehavior');
        MessagePacketType.DOTA_UM_QOP_ARCANA_SUMMARY.proto = um.lookupType('CDOTAUserMsg_QoP_ArcanaSummary');
        MessagePacketType.DOTA_UM_HOT_POTATO_CREATED.proto = um.lookupType('CDOTAUserMsg_HotPotato_Created');
        MessagePacketType.DOTA_UM_HOT_POTATO_EXPLODED.proto = um.lookupType('CDOTAUserMsg_HotPotato_Exploded');
        MessagePacketType.DOTA_UM_WK_ARCANA_PROGRESS.proto = um.lookupType('CDOTAUserMsg_WK_Arcana_Progress');
        MessagePacketType.DOTA_UM_GUILD_CHALLENGE_PROGRESS.proto = um.lookupType('CDOTAUserMsg_GuildChallenge_Progress');
        MessagePacketType.DOTA_UM_WR_ARCANA_PROGRESS.proto = um.lookupType('CDOTAUserMsg_WRArcanaProgress');
        MessagePacketType.DOTA_UM_WR_ARCANA_SUMMARY.proto = um.lookupType('CDOTAUserMsg_WRArcanaSummary');
        MessagePacketType.DOTA_UM_EMPTY_ITEM_SLOT_ALERT.proto = um.lookupType('CDOTAUserMsg_EmptyItemSlotAlert');
        MessagePacketType.DOTA_UM_AGHS_STATUS_ALERT.proto = um.lookupType('CDOTAUserMsg_AghsStatusAlert');
        MessagePacketType.DOTA_UM_PING_CONFIRMATION.proto = um.lookupType('CDOTAUserMsg_PingConfirmation');
        MessagePacketType.DOTA_UM_MUTED_PLAYERS.proto = um.lookupType('CDOTAUserMsg_MutedPlayers');
        MessagePacketType.DOTA_UM_CONTEXTUAL_TIP.proto = um.lookupType('CDOTAUserMsg_ContextualTip');
        MessagePacketType.DOTA_UM_CHAT_MESSAGE.proto = um.lookupType('CDOTAUserMsg_ChatMessage');
        MessagePacketType.DOTA_UM_NEUTRAL_CAMP_ALERT.proto = um.lookupType('CDOTAUserMsg_NeutralCampAlert');
        MessagePacketType.DOTA_UM_ROCK_PAPER_SCISSORS_STARTED.proto = um.lookupType('CDOTAUserMsg_RockPaperScissorsStarted');
        MessagePacketType.DOTA_UM_ROCK_PAPER_SCISSORS_FINISHED.proto = um.lookupType('CDOTAUserMsg_RockPaperScissorsFinished');
        MessagePacketType.DOTA_UM_DUEL_OPPONENT_KILLED.proto = um.lookupType('CDOTAUserMsg_DuelOpponentKilled');
        MessagePacketType.DOTA_UM_DUEL_ACCEPTED.proto = um.lookupType('CDOTAUserMsg_DuelAccepted');
        MessagePacketType.DOTA_UM_DUEL_REQUESTED.proto = um.lookupType('CDOTAUserMsg_DuelRequested');
        MessagePacketType.DOTA_UM_MUERTA_RELEASE_EVENT_ASSIGNED_TARGET_KILLED.proto = um.lookupType('CDOTAUserMsg_MuertaReleaseEvent_AssignedTargetKilled');
        MessagePacketType.DOTA_UM_PLAYER_DRAFT_SUGGEST_PICK.proto = um.lookupType('CDOTAUserMsg_PlayerDraftSuggestPick');
        MessagePacketType.DOTA_UM_PLAYER_DRAFT_PICK.proto = um.lookupType('CDOTAUserMsg_PlayerDraftPick');
        MessagePacketType.DOTA_UM_UPDATE_LINEAR_PROJECTILE_CP_DATA.proto = um.lookupType('CDOTAUserMsg_UpdateLinearProjectileCPData');
        MessagePacketType.DOTA_UM_GIFT_PLAYER.proto = um.lookupType('CDOTAUserMsg_GiftPlayer');
        MessagePacketType.DOTA_UM_FACET_PING.proto = um.lookupType('CDOTAUserMsg_FacetPing');
        MessagePacketType.DOTA_UM_INNATE_PING.proto = um.lookupType('CDOTAUserMsg_InnatePing');
        MessagePacketType.DOTA_UM_ROSHAN_TIMER.proto = um.lookupType('CDOTAUserMsg_RoshanTimer');
        MessagePacketType.DOTA_UM_NEUTRAL_CRAFT_AVAILABLE.proto = um.lookupType('CDOTAUserMsg_NeutralCraftAvailable');
        MessagePacketType.DOTA_UM_TIMER_ALERT.proto = um.lookupType('CDOTAUserMsg_TimerAlert');
        MessagePacketType.DOTA_UM_MADSTONE_ALERT.proto = um.lookupType('CDOTAUserMsg_MadstoneAlert');
        MessagePacketType.DOTA_UM_COURIER_LEFT_FOUNTAIN_ALERT.proto = um.lookupType('CDOTAUserMsg_CourierLeftFountainAlert');
        MessagePacketType.DOTA_UM_MONSTER_HUNTER_INVESTIGATIONS_AVAILABLE.proto = um.lookupType('CDOTAUserMsg_MonsterHunter_InvestigationsAvailable');
        MessagePacketType.DOTA_UM_MONSTER_HUNTER_INVESTIGATION_GAME_STATE.proto = um.lookupType('CDOTAUserMsg_MonsterHunter_InvestigationGameState');
        MessagePacketType.DOTA_UM_MONSTER_HUNTER_HUNT_ALERT.proto = um.lookupType('CDOTAUserMsg_MonsterHunter_HuntAlert');
        MessagePacketType.DOTA_UM_TORMENTOR_TIMER.proto = um.lookupType('CDOTAUserMsg_TormentorTimer');
        MessagePacketType.DOTA_UM_KILL_EFFECT.proto = um.lookupType('CDOTAUserMsg_KillEffect');
        MessagePacketType.DOTA_UM_GIVE_ITEM.proto = um.lookupType('CDOTAUserMsg_GiveItem');
    }
}

export default Bootstrap;
