name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      FILES: "36126255-5637 36126420-5637 37289286-5678 38969017-5768"
      S3: "https://deadem.s3.us-east-1.amazonaws.com"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: List versions
        run: node -v && npm -v

      - name: Install dependencies
        run: rm -rf node_modules && rm package-lock.json && npm i

      - name: Generate cache key
        id: hash
        run: |
          echo "key=$(echo $FILES | sha256sum | cut -c1-16)" >> $GITHUB_OUTPUT

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: demos
          key: s3-demos-${{ steps.hash.outputs.key }}

      - name: Download demos from S3
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p demos
          for file in $FILES; do
            echo "Downloading $file.dem"
            curl -L -o demos/$file.dem $S3/deadlock/demos/$file.dem
            echo "Downloaded $file.dem"
          done

      - name: List demo files
        run: ls -lh demos

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: demos
          key: s3-demos-${{ steps.hash.outputs.key }}

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run event consistency test for multithreaded parser
        run: node ./packages/examples-node/scripts/00_multithread_test.js

      - name: Run parser for multiple demo files
        run: node ./packages/examples-node/scripts/02_parse_multiple.js --matches="$FILES"
